

package com.duckduckgo.autofill.impl.jsbridge.request

data class AutofillStoreFormDataRequest(
    val credentials: AutofillStoreFormDataCredentialsRequest?,
)

data class AutofillStoreFormDataCredentialsRequest(
    val username: String?,
    val password: String?,
    val autogenerated: Boolean = false,
)
